# this script uses the devel-next version of the epitopes package:
# > devtools::install_github("fcampelo/epitopes@devel-next", force = TRUE)

library(dplyr)

ncpus <- parallel::detectCores() - 1

# orgID    <- 6282    # O. volvulus
# savefile <- "./ov_data.rds"

# orgID    <- 2697049 # SARS-Cov-2
# savefile <- "./data/sarscov2_data.rds"

orgID    <- 10376 # Epstein-Barr virus
savefile <- "./data/ebv_data.rds"


epitopes <- readRDS("./data/epitopes.rds") # Generated by get_IEDB() followed by get_LBCE()
proteins <- readRDS("./data/proteins.rds") # Generated by get_proteins()
taxonomy <- readRDS("./data/taxonomy.rds") # Generated by get_taxonomy()

t0 <- Sys.time()


peptides.list <- epitopes %>%
  filter_epitopes(orgIDs        = orgID,
                  orgID_column  = "sourceOrg_id",
                  hostID_column = "host_id",
                  tax_list      = taxonomy) %>%
  consolidate_data(proteins, only_exact = FALSE, ncpus = ncpus) %>%
  extract_peptides(min_peptide = 8, max_epitope = 25) %>%
  make_data_splits(proteins    = proteins,
                   split_prop  = c(.6,.4),                            # <--- desired split ratios
                   similarity_threshold = .75,
                  split_names = paste0("Fold_", 1:2),                # <--- split names
                   ncpus = ncpus) %>%
  calc_features(local.features = c("AAC", "CTDC", "CTDD", "CTDT",     # <--- local features are calculated for the 15-AA windows and added to peptides.list$df
                                   "BLOSUM", "Entropy",
                                   "MolWeight", "AAtypes", "Atoms"),
                global.features = c("AAC", "DC", "CTDC", "CTDD",      # <--- global features are calculated at the full protein level and added to peptides.list$proteins (needs a data join on df later, before training the models)
                                    "CTDT", "CTriad", "SOCN",
                                    "Entropy", "MolWeight", "AAtypes"),
                ncpus = ncpus)

# peptides.list will be a list with the full information on the resulting data,
# peptides.list$df       - windowed dataframe, incl. local features and data split information
# peptides.list$peptides - dataframe with information about the (non-windowed) peptides.
# peptides.list$proteins - dataframe of protein information, incl. global features.
# peptides.list$peptide.attrs  - attributes related to how the peptides were extracted
# peptides.list$peptide.attrs  - attributes related to how the data splits were defined
# peptides.list$feature.attrs  - attributes related to which features were calculated


t1 <- Sys.time()
message("Elapsed time: ", signif(t1 - t0, 3), " ", units(t1 - t0))
saveRDS(peptides.list, savefile)
