#' Calculate qualitative aminoacid composition of peptides
#'
#' This function is used to calculate the percent composition of peptides, in
#' terms of nine AA types: "Tiny", "Small", "Aliphatic", "Aromatic",
#' "NonPolar", "Polar", "Charged", "Basic" and "Acidic".
#'
#' This function is a direct adaptation of [Peptides::aaComp()]
#'
#' @param df a *data.table* of class *windowed_epit_dt* or *windowed_prot_dt*,
#'        generated by [make_window_df()]
#' @param ncpus positive integer, number of cores to use
#'
#' @return updated **df** data.table containing the AA percentage features
#' appended as columns.
#'
#' @author Felipe Campelo (\email{f.campelo@@aston.ac.uk});
#'         Jodie Ashford (\email{ashfojsm@@aston.ac.uk})
#'
calc_aa_composition <- function(df, ncpus){

  cat("\nCalculating AA composition\n")

  AAtypes <- list(Tiny      = c("A", "C", "G", "S", "T"),
                  Small     = c("A", "B", "C", "D", "G", "N", "P", "S", "T", "V"),
                  Aliphatic = c("A", "I", "L", "V"),
                  Aromatic  = c("F", "H", "W", "Y"),
                  NonPolar  = c("A", "C", "F", "G", "I", "L", "M", "P", "V", "W", "Y"),
                  Polar     = c("D", "E", "H", "K", "N", "Q", "R", "S", "T", "Z"),
                  Charged   = c("B", "D", "E", "H", "K", "R", "Z"),
                  Basic     = c("H", "K", "R"),
                  Acidic    = c("B", "D", "E", "Z"))

  cl <- set_mc(ncpus)
  tmp <- pbapply::pblapply(cl  = cl,
                           X   = df$Info_window_seq,
                           FUN = feat_AAComp,
                           AAtypes = AAtypes)
  close_mc(cl)

  tmp        <- data.table::rbindlist(tmp, use.names = TRUE)
  names(tmp) <- paste0("feat_Perc_", names(tmp))
  newvars    <- names(tmp)

  return(cbind(df, tmp))
}
