#' Calculate frequencies of N-peptides
#'
#' This function is used to calculate the frequencies of N-peptide subsequences
#' for each peptide
#'
#' @param df a *data.table* of class *windowed_epit_dt* or *windowed_prot_dt*,
#'        generated by [make_window_df()]
#' @param N the length of the subsequences to consider.
#' @param ncpus positive integer, number of cores to use
#'
#' @return updated **df** data.table containing the N-peptide frequencies
#'
#' @author Felipe Campelo (\email{f.campelo@@aston.ac.uk});
#'         Jodie Ashford (\email{ashfojsm@@aston.ac.uk})
#'
#' @export
#'
calc_Npeptide_composition <- function(df, N, ncpus){

  # Creates a list of tables contaning the dipeptide percentages for each window sequence in df
  cat(paste0("\nCalculating ", N, "-mer composition\n"))

  tmp <- mypblapply(ncpus = ncpus,
                    X     = df$Info_window_seq,
                    FUN   = feat_NPep,
                    N     = N)

  # Add a dummy element with all possible n-mers
  dummy <- as.data.frame(matrix(0, ncol = 20 ^ N, nrow = 1))
  args <- vector(mode = "list", length = N)
  for (i in seq_along(args)) args[[i]] <- get_aa_codes()
  names(dummy) <- apply(X   = do.call(expand.grid, args),
                        FUN = paste, MARGIN = 1, collapse = "")
  tmp[[length(tmp) + 1]] <- dummy

  # Binds results
  tmp <- data.table::rbindlist(tmp, use.names = TRUE, fill = TRUE)
  tmp[is.na(tmp)] <- 0

  # Removes dummy observation
  tmp <- tmp[-nrow(tmp), ]

  names(tmp) <- paste0("feat_Perc_", names(tmp))

  return(cbind(df, tmp))
}
