#' Calculate sequence entropy of peptides
#'
#' This function is used to calculate the sequence entropies,
#' Entropy = -sum(p_k * log2(p_k))
#'
#' @param df a *data.table* of class *windowed_epit_dt* or *windowed_prot_dt*,
#'        generated by [make_window_df()]
#' @param ncpus positive integer, number of cores to use
#'
#' @return updated **df** data.table containing the sequence entropy of each
#'         peptide
#'
#' @author Felipe Campelo (\email{f.campelo@@aston.ac.uk});
#'         Jodie Ashford (\email{ashfojsm@@aston.ac.uk})
#'

calc_sequence_entropy <- function(df, ncpus){

  # Entropy = -SUM(p(e)log2[p(e)])
  cat("\nCalculating sequence entropy:\n")

  cl  <- set_mc(ncpus)
  tmp <- pbapply::pbsapply(cl  = cl,
                           X   = df$Info_window_seq,
                           FUN = feat_SeqEntr)
  close_mc(cl)

  return(cbind(df, feat_seq_entropy = as.numeric(tmp)))

}
