#' Calculate number of each type of atom in peptide sequences
#'
#' This function is used to calculate the number of specific atoms in each
#' peptide
#'
#' @param df a *data.table* of class *windowed_epit_dt* or *windowed_prot_dt*,
#'        generated by [make_window_df()]
#' @param ncpus positive integer, number of cores to use
#'
#' @return updated **df** data.table containing the number of atoms of elements
#'         C, H, O, N and S.
#'
#' @author Felipe Campelo (\email{f.campelo@@aston.ac.uk});
#'         Jodie Ashford (\email{ashfojsm@@aston.ac.uk})
#'
calc_number_of_atoms <- function(df, ncpus){

  cat("\nCalculating atomic composition:\n")

  # Load AA properties
  aa_prop <- readRDS(system.file("extdata", "amino_acid_propensity.rds",
                                 package = "epitopes"))
  aa_prop <- aa_prop[, c("One_letter_code",
                         "Number_of_carbon_atoms_in_aa",
                         "Number_of_hydrogen_atoms_in_aa",
                         "Number_of_nitrogen_atoms_in_aa",
                         "Number_of_oxygen_atoms_in_aa",
                         "Number_of_sulphur_atoms_in_aa")]
  names(aa_prop)[-1] <- c("C", "H", "N", "O", "S")

  cl <- set_mc(ncpus)
  tmp <- pbapply::pblapply(cl  = cl,
                           X   = df$Info_window_seq,
                           FUN = feat_NumAtom,
                           aa_prop = aa_prop)
  close_mc(cl)

  tmp <- data.table::rbindlist(tmp, use.names = TRUE)
  names(tmp) <- paste0("feat_", names(tmp), "_atoms")

  return(cbind(df, tmp))

}
