#' Calculate sequence entropy of peptides
#'
#' This function is used to calculate the sequence entropies,
#' Entropy = -sum(p_k * log2(p_k))
#'
#' @param df a *data.table* of class *windowed_epit_dt* or *windowed_prot_dt*,
#'        generated by [make_window_df()]
#' @param cl either a cluster object or a positive integer.
#'
#' @return updated **df** data.table containing the sequence entropy of each
#'         peptide
#'
#' @author Felipe Campelo (\email{f.campelo@@aston.ac.uk});
#'         Jodie Ashford (\email{ashfojsm@@aston.ac.uk})
#'

calc_sequence_entropy <- function(df, cl){

  # Entropy = -SUM(p(e)log2[p(e)])
  cat("\nCalculating sequence entropy:\n")
  tmp <- pbapply::pbsapply(cl  = cl,
                           X   = df$Info_window_seq,
                           FUN = function(x){
                             cnts <- stringr::str_count(x, LETTERS)
                             cnts <- cnts[cnts > 0] / sum(cnts)
                             -sum(cnts * log2(cnts))
                           })

  return(cbind(df, feat_seq_entropy = as.numeric(tmp)))

}
