#' Calculate conjoint triads
#'
#' This function is used to calculate the conjoint triad frequencies for
#' each peptide
#'
#' @param df a *data.table* of class *windowed_epit_dt* or *windowed_prot_dt*,
#'        generated by [make_window_df()]
#' @param cl either a cluster object or a positive integer.
#'
#' @return updated **df** data.table containing the conjoint triad frequencies
#'
#' @author Felipe Campelo (\email{f.campelo@@aston.ac.uk});
#'         Jodie Ashford (\email{ashfojsm@@aston.ac.uk})
#'
calc_conjoint_triads <- function(df, cl){

  cat("\nCalculating conjoint triads:\n")

  # Load AA properties
  aa_prop <- readRDS(system.file("extdata", "amino_acid_propensity.rds",
                                 package = "epitopes"))
  aa_prop <- aa_prop[, c("One_letter_code", "CT_group")]

  tmp <- pbapply::pblapply(cl  = cl,
                           X   = df$Info_window_seq,
                           FUN = function(x, aa_prop){
                             idx <- stringr::str_locate(paste(aa_prop$One_letter_code,
                                                              collapse = ""),
                                                        strsplit(x, "")[[1]])[, 1]
                             x <- paste(aa_prop$CT_group[idx], collapse = "")
                             ct <- stringr::str_sub(x,
                                                    start = 1:(nchar(x) - 2),
                                                    end   = 3:nchar(x))

                             # Return percent occurrence of CTs
                             as.data.frame(t(as.matrix(table(ct)))) / length(ct)
                           },
                           aa_prop = aa_prop)

  # Add a dummy element with all possible triads
  dummy <- as.data.frame(matrix(0, ncol = 7 ^ 3, nrow = 1))
  names(dummy) <- apply(X   = expand.grid(0:6, 0:6, 0:6),
                        FUN = paste, MARGIN = 1, collapse = "")
  tmp[[length(tmp) + 1]] <- dummy

  # Binds results
  tmp <- data.table::rbindlist(tmp, use.names = TRUE, fill = TRUE)
  tmp[is.na(tmp)] <- 0

  # Removes dummy observation
  tmp <- tmp[-nrow(tmp), ]

  names(tmp) <- paste0("feat_CT", names(tmp))

  return(cbind(df, tmp))
}
