#' Calculate frequencies of N-peptides
#'
#' This function is used to calculate the frequencies of N-peptide subsequences
#' for each peptide
#'
#' @param df a *data.table* of class *windowed_epit_dt* or *windowed_prot_dt*,
#'        generated by [make_window_df()]
#' @param N the length of the subsequences to consider.
#' @param cl either a cluster object or a positive integer.
#'
#' @return updated **df** data.table containing the N-peptide frequencies
#'
#' @author Felipe Campelo (\email{f.campelo@@aston.ac.uk});
#'         Jodie Ashford (\email{ashfojsm@@aston.ac.uk})
#'
#' @export
#'
calc_Npeptide_composition <- function(df, N, cl){

  # Creates a list of tables contaning the dipeptide percentages for each window sequence in df
  cat(paste0("\n Calculating ", N, "-mer composition:\n"))

  myf <- function(x, N){
    i1 <- 1:(nchar(x) - N + 1)
    i2 <- i1 + N - 1
    y <- stringr::str_sub(x, i1, i2)
    as.data.frame(t(as.matrix(table(y)))) / length(y)
  }
  if (ismc(cl)){
    tmp <- pbapply::pblapply(cl  = cl,
                             X   = df$Info_window_seq,
                             FUN = myf,
                             N   = N,
                             mc.preschedule = FALSE)
  } else {
    tmp <- pbapply::pblapply(cl  = cl,
                             X   = df$Info_window_seq,
                             FUN = myf,
                             N   = N)
  }

  # Add a dummy element with all possible triads
  dummy <- as.data.frame(matrix(0, ncol = 20 ^ N, nrow = 1))
  args <- vector(mode = "list", length = N)
  for (i in seq_along(args)) args[[i]] <- get_aa_codes()
  names(dummy) <- apply(X   = do.call(expand.grid, args),
                        FUN = paste, MARGIN = 1, collapse = "")
  tmp[[length(tmp) + 1]] <- dummy

  # Binds results
  tmp <- data.table::rbindlist(tmp, use.names = TRUE, fill = TRUE)
  tmp[is.na(tmp)] <- 0

  # Removes dummy observation
  tmp <- tmp[-nrow(tmp), ]

  names(tmp) <- paste0("feat_Perc_", names(tmp))

  return(cbind(df, tmp))
}
