#' Calculate molecular weight of peptide sequences
#'
#' This function is used to calculate the molecular weights for each peptide
#'
#' @param df a *data.table* of class *windowed_epit_dt* or *windowed_prot_dt*,
#'        generated by [make_window_df()]
#' @param ncpus positive integer, number of cores to use
#'
#' @return updated **df** data.table containing the molecular weight features
#' appended as columns.
#'
#' @author Felipe Campelo (\email{f.campelo@@aston.ac.uk});
#'         Jodie Ashford (\email{ashfojsm@@aston.ac.uk})
#'

calc_molecular_weight <- function(df, ncpus){

  cat("\nCalculating molecular weight\n")

  # Load AA properties
  aa_prop <- readRDS(system.file("extdata", "amino_acid_propensity.rds",
                                 package = "epitopes"))
  aa_prop <- aa_prop[, c("One_letter_code", "Amino_acid_molecular_weight")]

  tmp <- mypblapply(ncpus   = ncpus,
                    X       = df$Info_window_seq,
                    FUN     = feat_MolWei,
                    aa_prop = aa_prop)

  return(cbind(df, feat_molecular_weight = unlist(tmp)))
}
