#' Calculate molecular weight of peptide sequences
#'
#' This function is used to calculate the molecular weights for each peptide
#'
#' @param df a *data.table* of class *windowed_epit_dt* or *windowed_prot_dt*,
#'        generated by [make_window_df()]
#' @param cl either a cluster object or a positive integer.
#'
#' @return updated **df** data.table containing the molecular weight features
#' appended as columns.
#'
#' @author Felipe Campelo (\email{f.campelo@@aston.ac.uk});
#'         Jodie Ashford (\email{ashfojsm@@aston.ac.uk})
#'

calc_molecular_weight <- function(df, cl){

  cat("\nCalculating molecular weight:\n")

  # Load AA properties
  aa_prop <- readRDS(system.file("extdata", "amino_acid_propensity.rds",
                                 package = "epitopes"))
  aa_prop <- aa_prop[, c("One_letter_code", "Amino_acid_molecular_weight")]


  tmp <- pbapply::pbsapply(cl  = cl,
                           X   = df$Info_window_seq,
                           FUN = function(x, aa_prop){
                             cnts <- stringr::str_count(x, aa_prop$One_letter_code)
                             sum(cnts * aa_prop$Amino_acid_molecular_weight)
                           },
                           aa_prop = aa_prop)

  return(cbind(df, feat_molecular_weight = as.numeric(tmp)))
}
