#' Calculate number of each type of atom in peptide sequences
#'
#' This function is used to calculate the number of specific atoms in each
#' peptide
#'
#' @param df a *data.table* of class *windowed_epit_dt* or *windowed_prot_dt*,
#'        generated by [make_window_df()]
#' @param cl either a cluster object or a positive integer.
#'
#' @return updated **df** data.table containing the number of atoms of elements
#'         C, H, O, N and S.
#'
#' @author Felipe Campelo (\email{f.campelo@@aston.ac.uk});
#'         Jodie Ashford (\email{ashfojsm@@aston.ac.uk})
#'
calc_number_of_atoms <- function(df, cl){

  cat("\nCalculating atomic composition:\n")

  # Load AA properties
  aa_prop <- readRDS(system.file("extdata", "amino_acid_propensity.rds",
                                 package = "epitopes"))
  aa_prop <- aa_prop[, c("One_letter_code",
                         "Number_of_carbon_atoms_in_aa",
                         "Number_of_hydrogen_atoms_in_aa",
                         "Number_of_nitrogen_atoms_in_aa",
                         "Number_of_oxygen_atoms_in_aa",
                         "Number_of_sulphur_atoms_in_aa")]
  names(aa_prop)[-1] <- c("C", "H", "N", "O", "S")

  myf <- function(x, aa_prop){
    cnts <- stringr::str_count(x, aa_prop$One_letter_code)
    as.data.frame(t(colSums(cnts * aa_prop[, -1])))
  }
  if (ismc(cl)){
    tmp <- pbapply::pblapply(cl  = cl,
                             X   = df$Info_window_seq,
                             FUN = myf,
                             aa_prop = aa_prop,
                             mc.preschedule = FALSE)
  } else {
    tmp <- pbapply::pblapply(cl  = cl,
                             X   = df$Info_window_seq,
                             FUN = myf,
                             aa_prop = aa_prop)
  }

  tmp <- data.table::rbindlist(tmp, use.names = TRUE)
  names(tmp) <- paste0("feat_", names(tmp), "_atoms")

  return(cbind(df, tmp))
}
