#' Filter epitopes by taxonomy and host
#'
#' Filters an epitope dataframe by source organism and/or host IDs.
#'
#' @param df a data frame containing epitope data
#' @param orgIDs vector of organism taxon IDs that we want to retain
#'        (using `df$sourceOrg_id`).
#' @param hostIDs vector of host taxon IDs that we want to retain
#'        (using `df$host_id`).
#' @param removeIDs vector of organism taxon IDs that we want to remove
#'        (using `df$sourceOrg_id`).
#' @param orgID_column name of the column in `df` containing the source organism IDs
#' @param hostID_column name of the column in `df` containing the host IDs
#' @param tax_list taxonomy list (generated by [get_taxonomy()])
#'
#' @return data frame with epitope data, filtered by the criteria in **orgIDs**,
#' **hostIDs** and **removeIDs**.
#'
#' @author Felipe Campelo (\email{f.campelo@@aston.ac.uk})
#'
#' @export
#'

filter_epitopes <- function(df,
                            orgIDs    = NULL,
                            hostIDs   = NULL,
                            removeIDs = NULL,
                            orgID_column = "sourceOrg_id",
                            hostID_column = "host_id",
                            tax_list  = NULL) {

  # ========================================================================== #
  # Sanity checks and initial definitions
  id_classes <- c("NULL", "numeric", "integer", "character")
  assertthat::assert_that(is.data.frame(df),
                          class(orgIDs)    %in% id_classes,
                          class(hostIDs)   %in% id_classes,
                          class(removeIDs) %in% id_classes,
                          is.character(orgID_column), length(orgID_column) == 1,
                          is.character(hostID_column),
                          length(hostID_column) == 1,
                          is.list(tax_list))

  # Standardise relevant variables:
  ids <- data.frame(org  = as.character(df[, which(names(df) == orgID_column), drop = TRUE]),
                    host = as.character(df[, which(names(df) == hostID_column), drop = TRUE]))

  # Function to extract the relevant organism IDs using the taxonomy data
  fextr <- function(x, tid){
    ul <- c(x$Taxonomy$UID, x$UID)
    if(any(tid %in% ul)) return(x$UID)
  }

  # Function to get the filtering indices
  fmatch <- function(pat, trg){
    str <- unlist(strsplit(pat, split = ",", fixed = TRUE))
    any(str %in% trg)
  }

  # Filter by OrgIDs
  if (!is.null(orgIDs)){
    target_org  <- unlist(sapply(tax_list, FUN = fextr, tid = orgIDs))
    target_org  <- unique(c(target_org, orgIDs))
    idx1        <- which(sapply(ids$org, FUN = fmatch, trg = target_org))
    if(length(idx1) > 0){
      ids  <- ids[idx1, ]
      df   <- df[idx1, ]
    } else {
      ids <- numeric()
      df  <- numeric()
    }
  }

  # Filter by hostIDs
  if (!is.null(hostIDs) && nrow(df) > 0){
    target_host <- unlist(sapply(tax_list, FUN = fextr, tid = hostIDs))
    target_host <- unique(c(target_host, hostIDs))
    idx2        <- which(sapply(ids$host, FUN = fmatch, trg = target_host))
    if(length(idx2) > 0){
      ids  <- ids[idx2, ]
      df   <- df[idx2, ]
    } else {
      ids <- numeric()
      df  <- numeric()
    }
  }

  # Filter by removeIDs
  if (!is.null(removeIDs) && nrow(df) > 0){
    target_rm   <- unlist(sapply(tax_list, FUN = fextr, tid = removeIDs))
    target_rm   <- unique(c(target_rm, removeIDs))
    idx3        <- which(sapply(ids$org, FUN = fmatch, trg = target_rm))
    if (length(idx3) > 0){
      ids  <- ids[-idx3, ]
      df   <- df[-idx3, ]
    }
  }

  return(df)

}
